FROM node:20-alpine

RUN corepack enable && corepack prepare pnpm@9.15.0 --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./


RUN pnpm install

COPY . .

EXPOSE 3001

CMD ["pnpm", "start"]