FROM node:24-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml ./


RUN pnpm install

COPY . .

EXPOSE 3001

CMD ["pnpm", "start"]
