services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    ports:
      - "${UI_PORT:-3001}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - REACT_APP_API_URL=${REACT_APP_API_URL}
